# Non Graded Challenge 5 - Linear Algebra - Eigendecomposition

## Assignment Instructions

Apakah $\begin{bmatrix}1 \\3\end{bmatrix}$ adalah eigenvector dari $\begin{bmatrix}1 & -1\\6 &-4 \end{bmatrix}$? Jika iya, berapakah eigenvalue-nya?

---
## Answer

Formula to of eigen-vector and eigen-value : 

> A⋅x = λx

<br>

So, if we want to get eigen-value : 

> λ = A⋅x/x

Notes : 
* A : A vector.
* x : Eigen-vector.
* λ : Eigen-value

In [1]:
# Define the Matrix

import numpy as np

A = np.array([
              [1, -1], 
              [6, 4]])
A

array([[ 1, -1],
       [ 6,  4]])

In [2]:
# Define the Eigen Vector

B = np.array([1, 3])
B

array([1, 3])

In [3]:
# Display A@B/B

A @ B / B

array([-2.,  6.])

**Conclusion :** 

Because it display `-2` and `6`, we can say that $\begin{bmatrix}1 \\3\end{bmatrix}$ is **not** eigen vector of $\begin{bmatrix}1 & -1\\6 &-4 \end{bmatrix}$

---
### Example of a matrix with its eigen-vector

Vector $\begin{bmatrix}1 \\2\end{bmatrix}$ is eigen-vector of matrix $\begin{bmatrix}1 & 2\\2 & 4 \end{bmatrix}$

In [4]:
# Define a Vector

v = np.array([1, 2])
v

array([1, 2])

In [5]:
# Define the Matrix

T = np.array([[1,2], [2,4]])
T

array([[1, 2],
       [2, 4]])

In [6]:
# Display T@v/v

T @ v / v

array([5., 5.])

**Conclusion :** 

Because it display `5` on each element, we can say that Vector $\begin{bmatrix}1 \\2\end{bmatrix}$ is eigen-vector of matrix $\begin{bmatrix}1 & 2\\2 & 4 \end{bmatrix}$